### ISSUE TITLE
Editing Preroll Call Script

### ISSUE THREAD

**Issue by OcifferAction** [jcostom/rollerblades#1]
First of all, thank you for creating this. I've been pulling my hair for days trying to determine why Rollarr or Plex-Meta-Manager wouldn't change my prerolls. Turns out it was throwing the same error you mentioned in the Plex-API Discord. I'm utilizing your Docker container and have successfully changed my Plex Prerolls fairly easily.

My issue is that the rollerblades.py only sees pridemonth and no other months I put in the prerolls.json. I'm attempting to have all the holidays update prerolls in Plex automatically, but I'm not sure how to edit rollerblades.py within Docker to fit my needs.

I've attached my prerolls.json in .txt form with some comments as an example for what I'm trying to do. I believe my issues could all be resolved with just allowing the specification of spanning days in the holiday section.
[prerolls.txt](https://github.com/jcostom/rollerblades/files/10032804/prerolls.txt)

Again, thank you so much for making this as I finally feel like I'm making headway into my preroll automations.

EDIT: I've created a fork to change around what I wanted in rollerblades.py

**Comment by jcostom** [comment]
Thanks for the note - glad to hear you're making use of the code! Yeah, I was thinking about just generalizing the SPECIAL_MONTHS section, rather than just simply setting up June. I just need a little time to have a look at it. I should get some time over the weekend to tinker a bit. Stay tuned.

**Comment by jcostom** [comment]
Ok, v0.6 is now available. I generalized the month-specific feature, slightly changed the format of the config file as well. I haven't implemented date ranges in this release though. I'm noodling an elegant way to do that. When one hits me, or someone contributes one, I'll merge it.

This release should address the month problem you were having.
