### ISSUE TITLE
A "daily" path but without the "./weekday"

### ISSUE THREAD

**Issue by bassterror** [jcostom/rollerblades#27]
Hello, first of all thank you for the awesome script.
Is there a way to set up one path that is the default path for every day except the Holidays? I have a directory "/preroll/daily" and if I use that in the "DAILYPATH" the scripts concatenates "/someweekday" with it. Obviously, I cannot understand something here. How can I setup a default path so Plex picks up a random video from it, and if it's a holiday it would pick a video from a different path (ex. "/preroll/christmas")?

Thank you in advance and keep up the good work!

**Comment by jcostom** [comment]
There's a quick & dirty way to do it with a directory and some symlinks. I just tested it successfully. I just popped into my $DAILYPATH, made a directory called "vids", moved all my mp4's into there, then made symlinks, one for each day of the week. It looks like this:

```
$ ls -lR
.:
total 28
lrwxrwxrwx+ 1 jcostom users   4 Feb 29 17:29 friday -> vids/
lrwxrwxrwx+ 1 jcostom users   4 Feb 29 17:29 monday -> vids/
lrwxrwxrwx+ 1 jcostom users   4 Feb 29 17:29 saturday -> vids/
lrwxrwxrwx+ 1 jcostom users   4 Feb 29 17:29 sunday -> vids/
lrwxrwxrwx+ 1 jcostom users   4 Feb 29 17:29 thursday -> vids/
lrwxrwxrwx+ 1 jcostom users   4 Feb 29 17:29 tuesday -> vids/
drwxr-xr-x+ 1 jcostom users 176 Feb 29 17:29 vids/
lrwxrwxrwx+ 1 jcostom users   4 Feb 29 17:29 wednesday -> vids/

./vids:
total 19416
-rw-r--r--+ 1 jcostom users 6804973 Oct 27  2022 friday.mp4
-rw-r--r--+ 1 jcostom users 1885344 Oct 27  2022 monday.mp4
-rw-r--r--+ 1 jcostom users 5267240 Oct 27  2022 nfdark.mp4
-rw-r--r--+ 1 jcostom users  238205 Oct 27  2022 saturday.mp4
-rw-r--r--+ 1 jcostom users 3890350 Oct 27  2022 sunday.mp4
-rw-r--r--+ 1 jcostom users  368506 Oct 27  2022 thursday.mp4
-rw-r--r--+ 1 jcostom users  747473 Oct 27  2022 tuesday.mp4
-rw-r--r--+ 1 jcostom users  666296 Oct 27  2022 wednesday.mp4

```

Logs showed:

```
[INFO] [29 Feb 2024 17:30:02 EST] Startup rollerblades.py/1.1.2.
[INFO] [29 Feb 2024 17:30:02 EST] Loaded in prerolls data from /config/prerolls.json.
[INFO] [29 Feb 2024 17:30:02 EST] Current preroll is: /prerolls/daily/thursday.mp4.
[INFO] [29 Feb 2024 17:30:02 EST] Change /prerolls/daily/thursday.mp4 to /prerolls/daily/thursday/friday.mp4;/prerolls/daily/thursday/monday.mp4;/prerolls/daily/thursday/nfdark.mp4;/prerolls/daily/thursday/saturday.mp4;/prerolls/daily/thursday/sunday.mp4;/prerolls/daily/thursday/thursday.mp4;/prerolls/daily/thursday/tuesday.mp4;/prerolls/daily/thursday/wednesday.mp4.
```
So, that should do what you're looking for, correct?

**Comment by bassterror** [comment]
Thank you for your response. It's a good idea. I'll try it tomorrow and comment back.

**Comment by jcostom** [comment]
A little more (possibly?) light on things..  This is the prerolls.json file I'm using:

```
{
    "MONTHS": {
        "06": "/prerolls/months/june"
    },
    "HOLIDAYS": {
        "0401": "/prerolls/holiday/aprilfool",
        "1224": "/prerolls/holiday/christmas",
        "1225": "/prerolls/holiday/christmas",
        "1226": "/prerolls/holiday/christmas",
        "0214": "/prerolls/holiday/valentines",
        "1030": "/prerolls/holiday/halloween",
        "1031": "/prerolls/holiday/halloween"
    },
    "DAILYPATH": "/prerolls/daily"
}
```

**Comment by bassterror** [comment]
Thank you! The symlink trick worked. You should consider the option for a "default" dir in the JSON. I think it will be a good addition to the script.

**Comment by bassterror** [comment]
Actually, I played with the volume mounts and it worked too. :)

The YAML:
```
    volumes:
      - ./appdata:/config
      - /etc/localtime:/etc/localtime:ro
      - /volume1/Plex/preroll/default:/volume1/Plex/preroll/daily/monday
      - /volume1/Plex/preroll/default:/volume1/Plex/preroll/daily/tuesday
      - /volume1/Plex/preroll/default:/volume1/Plex/preroll/daily/wednesday
      - /volume1/Plex/preroll/default:/volume1/Plex/preroll/daily/thursday
      - /volume1/Plex/preroll/default:/volume1/Plex/preroll/daily/friday
      - /volume1/Plex/preroll/default:/volume1/Plex/preroll/daily/saturday
      - /volume1/Plex/preroll/default:/volume1/Plex/preroll/daily/sunday
      - /volume1/Plex/preroll/easter:/volume1/Plex/preroll/easter
      - /volume1/Plex/preroll/helloween:/volume1/Plex/preroll/helloween
      - /volume1/Plex/preroll/christmas:/volume1/Plex/preroll/christmas
```
and the JSON:
```
{
    "MONTHS": {
        "06": ""
    },
    "HOLIDAYS": {
        "1224": "/volume1/Plex/preroll/christmas",
        "1225": "/volume1/Plex/preroll/christmas",
        "1226": "/volume1/Plex/preroll/christmas",
        "1030": "/volume1/Plex/preroll/helloween",
        "1031": "/volume1/Plex/preroll/helloween",
        "0503": "/volume1/Plex/preroll/easter",
        "0504": "/volume1/Plex/preroll/easter",
        "0505": "/volume1/Plex/preroll/easter",
        "0506": "/volume1/Plex/preroll/easter"
    },
    "DAILYPATH": "/volume1/Plex/preroll/daily"
}
```

**Comment by jcostom** [comment]
Yup, that works too. Cheers!

**Comment by bassterror** [comment]
I'm sorry, but I was wrong.
The trick with the mounts doesn't work, because the paths imported to Plex are not real and Plex doesn't know what to do with them. To rollerblades this path "/volume1/Plex/preroll/daily" is a thing, but for Plex is non-existant. :)

Also, I couldn't make the trick with the symlink working. When I create a symlink `ln -s /volume1/Plex/preroll/default/ /volume1/Plex/preroll/daily/wednesday/` it creates a link to the "default" dir inside the "wednesday" dir. This isn't a solution because we want the content of the "default" inside "wednesday" not the dir itself. Am I doing something wrong here, or what?

What if I setup 12 identical month entries for the MONTHS option in the JSON, pointing to my default dir? If it happens to be Christmas will it overwrite the month setup for the dates of Christmas that I setup?
